site_name: PUEBI Daring
pages:
  - 'Beranda': 'index.md'
theme: 'readthedocs'
repo_name: 'Github'
repo_url: 'https://github.com/ridwan-arifin/eyd'
google_analytics: ['UA-80210173-1', 'auto']
markdown_extensions:
  - admonition